#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sat Apr 11 21:44:00 2020

@author: Sweta Kumari

"""

import numpy as np


class DecisionTree:
    def __init__(self):
        pass

    def fit(x, y):
        pass
    